export interface ILanguages {
    aar?: string
    abk?: string
    ace?: string
    ach?: string
    ada?: string
    ady?: string
    afa?: string
    afh?: string
    afr?: string
    ain?: string
    aka?: string
    akk?: string
    sqi?: string
    ale?: string
    alg?: string
    alt?: string
    amh?: string
    ang?: string
    anp?: string
    apa?: string
    ara?: string
    arc?: string
    arg?: string
    hye?: string
    arn?: string
    arp?: string
    art?: string
    arw?: string
    asm?: string
    ast?: string
    ath?: string
    aus?: string
    ava?: string
    ave?: string
    awa?: string
    aym?: string
    aze?: string
    bad?: string
    bai?: string
    bak?: string
    bal?: string
    bam?: string
    ban?: string
    eus?: string
    bas?: string
    bat?: string
    bej?: string
    bel?: string
    bem?: string
    ben?: string
    ber?: string
    bho?: string
    bih?: string
    bik?: string
    bin?: string
    bis?: string
    bla?: string
    bnt?: string
    bos?: string
    bra?: string
    bre?: string
    btk?: string
    bua?: string
    bug?: string
    bul?: string
    mya?: string
    byn?: string
    cad?: string
    cai?: string
    car?: string
    cat?: string
    cau?: string
    ceb?: string
    cel?: string
    cha?: string
    chb?: string
    che?: string
    chg?: string
    zho?: string
    chk?: string
    chm?: string
    chn?: string
    cho?: string
    chp?: string
    chr?: string
    chu?: string
    chv?: string
    chy?: string
    cmc?: string
    cnr?: string
    cop?: string
    cor?: string
    cos?: string
    cpe?: string
    cpf?: string
    cpp?: string
    cre?: string
    crh?: string
    crp?: string
    csb?: string
    cus?: string
    ces?: string
    dak?: string
    dan?: string
    dar?: string
    day?: string
    del?: string
    den?: string
    dgr?: string
    din?: string
    div?: string
    doi?: string
    dra?: string
    dsb?: string
    dua?: string
    dum?: string
    nld?: string
    dyu?: string
    dzo?: string
    efi?: string
    egy?: string
    eka?: string
    elx?: string
    eng?: string
    enm?: string
    epo?: string
    est?: string
    ewe?: string
    ewo?: string
    fan?: string
    fao?: string
    fat?: string
    fij?: string
    fil?: string
    fin?: string
    fiu?: string
    fon?: string
    fra?: string
    frm?: string
    fro?: string
    frr?: string
    frs?: string
    fry?: string
    ful?: string
    fur?: string
    gaa?: string
    gay?: string
    gba?: string
    gem?: string
    kat?: string
    deu?: string
    gez?: string
    gil?: string
    gla?: string
    gle?: string
    glg?: string
    glv?: string
    gmh?: string
    goh?: string
    gon?: string
    gor?: string
    got?: string
    grb?: string
    grc?: string
    ell?: string
    grn?: string
    gsw?: string
    guj?: string
    gwi?: string
    hai?: string
    hat?: string
    hau?: string
    haw?: string
    heb?: string
    her?: string
    hil?: string
    him?: string
    hin?: string
    hit?: string
    hmn?: string
    hmo?: string
    hrv?: string
    hsb?: string
    hun?: string
    hup?: string
    iba?: string
    ibo?: string
    isl?: string
    ido?: string
    iii?: string
    ijo?: string
    iku?: string
    ile?: string
    ilo?: string
    ina?: string
    inc?: string
    ind?: string
    ine?: string
    inh?: string
    ipk?: string
    ira?: string
    iro?: string
    ita?: string
    jav?: string
    jbo?: string
    jpn?: string
    jpr?: string
    jrb?: string
    kaa?: string
    kab?: string
    kac?: string
    kal?: string
    kam?: string
    kan?: string
    kar?: string
    kas?: string
    kau?: string
    kaw?: string
    kaz?: string
    kbd?: string
    kha?: string
    khi?: string
    khm?: string
    kho?: string
    kik?: string
    kin?: string
    kir?: string
    kmb?: string
    kok?: string
    kom?: string
    kon?: string
    kor?: string
    kos?: string
    kpe?: string
    krc?: string
    krl?: string
    kro?: string
    kru?: string
    kua?: string
    kum?: string
    kur?: string
    kut?: string
    lad?: string
    lah?: string
    lam?: string
    lao?: string
    lat?: string
    lav?: string
    lez?: string
    lim?: string
    lin?: string
    lit?: string
    lol?: string
    loz?: string
    ltz?: string
    lua?: string
    lub?: string
    lug?: string
    lui?: string
    lun?: string
    luo?: string
    lus?: string
    mkd?: string
    mad?: string
    mag?: string
    mah?: string
    mai?: string
    mak?: string
    mal?: string
    man?: string
    mri?: string
    map?: string
    mar?: string
    mas?: string
    msa?: string
    mdf?: string
    mdr?: string
    men?: string
    mga?: string
    mic?: string
    min?: string
    mis?: string
    mkh?: string
    mlg?: string
    mlt?: string
    mnc?: string
    mni?: string
    mno?: string
    moh?: string
    mon?: string
    mos?: string
    mul?: string
    mun?: string
    mus?: string
    mwl?: string
    mwr?: string
    myn?: string
    myv?: string
    nah?: string
    nai?: string
    nap?: string
    nau?: string
    nav?: string
    nbl?: string
    nde?: string
    ndo?: string
    nds?: string
    nep?: string
    new?: string
    nia?: string
    nic?: string
    niu?: string
    nno?: string
    nob?: string
    nog?: string
    non?: string
    nor?: string
    nqo?: string
    nso?: string
    nub?: string
    nwc?: string
    nya?: string
    nym?: string
    nyn?: string
    nyo?: string
    nzi?: string
    oci?: string
    oji?: string
    ori?: string
    orm?: string
    osa?: string
    oss?: string
    ota?: string
    oto?: string
    paa?: string
    pag?: string
    pal?: string
    pam?: string
    pan?: string
    pap?: string
    pau?: string
    peo?: string
    fas?: string
    phi?: string
    phn?: string
    pli?: string
    pol?: string
    pon?: string
    por?: string
    pra?: string
    pro?: string
    pus?: string
    que?: string
    raj?: string
    rap?: string
    rar?: string
    roa?: string
    roh?: string
    rom?: string
    ron?: string
    run?: string
    rup?: string
    rus?: string
    sad?: string
    sag?: string
    sah?: string
    sai?: string
    sal?: string
    sam?: string
    san?: string
    sas?: string
    sat?: string
    scn?: string
    sco?: string
    sel?: string
    sem?: string
    sga?: string
    sgn?: string
    shn?: string
    sid?: string
    sin?: string
    sio?: string
    sit?: string
    sla?: string
    slk?: string
    slv?: string
    sma?: string
    sme?: string
    smi?: string
    smj?: string
    smn?: string
    smo?: string
    sms?: string
    sna?: string
    snd?: string
    snk?: string
    sog?: string
    som?: string
    son?: string
    sot?: string
    spa?: string
    srd?: string
    srn?: string
    srp?: string
    srr?: string
    ssa?: string
    ssw?: string
    suk?: string
    sun?: string
    sus?: string
    sux?: string
    swa?: string
    swe?: string
    syc?: string
    syr?: string
    tah?: string
    tai?: string
    tam?: string
    tat?: string
    tel?: string
    tem?: string
    ter?: string
    tet?: string
    tgk?: string
    tgl?: string
    tha?: string
    bod?: string
    tig?: string
    tir?: string
    tiv?: string
    tkl?: string
    tlh?: string
    tli?: string
    tmh?: string
    tog?: string
    ton?: string
    tpi?: string
    tsi?: string
    tsn?: string
    tso?: string
    tuk?: string
    tum?: string
    tup?: string
    tur?: string
    tut?: string
    tvl?: string
    twi?: string
    tyv?: string
    udm?: string
    uga?: string
    uig?: string
    ukr?: string
    umb?: string
    und?: string
    urd?: string
    uzb?: string
    vai?: string
    ven?: string
    vie?: string
    vol?: string
    vot?: string
    wak?: string
    wal?: string
    war?: string
    was?: string
    cym?: string
    wen?: string
    wln?: string
    wol?: string
    xal?: string
    xho?: string
    yao?: string
    yap?: string
    yid?: string
    yor?: string
    ypk?: string
    zap?: string
    zbl?: string
    zen?: string
    zgh?: string
    zha?: string
    znd?: string
    zul?: string
    zun?: string
    zxx?: string
    zza?: string
}